apiVersion: v2
name: cert-manager-config
description: A Helm chart for cert-manager configuration including ClusterIssuers and CA certificates
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies: []

maintainers:
  - name: vjkancherla
    email: your-email@example.com

annotations:
  category: Security
  licenses: Apache-2.0