# helm-charts/istio-encryption-config/templates/destination-rule.yaml
{{- if .Values.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend-app-dr
  namespace: my-demo
  labels:
    {{- include "istio-encryption-config.labels" . | nindent 4 }}
spec:
  host: frontend-app
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: backend-app-dr
  namespace: my-demo
  labels:
    {{- include "istio-encryption-config.labels" . | nindent 4 }}
spec:
  host: backend-app
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}