# helm-charts/istio-encryption-config/templates/peer-authentication.yaml
{{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-peer-auth
  namespace: my-demo
  labels:
    {{- include "istio-encryption-config.labels" . | nindent 4 }}
spec:
  mtls:
    mode: STRICT
{{- end }}