apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-app.fullname" . }}-config
  namespace: my-demo
data:
  nginx.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}